t_fish_id = None  # 定义fish_id变量并赋默认值
t_fish_name = None
t_fish_picture_res = None
t_rarity_id = None
t_fishing_ground_id = None
t_fishing_ground_name = None
t_price = None
t_output = None
t_weight = None