version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://ooc_user:abc7902564@db:5432/ooc_db
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ooc_db
      - POSTGRES_USER=ooc_user
      - POSTGRES_PASSWORD=abc7902564
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: